"""JSON Schemas + descriptions for each tool, surfaced to MCP clients.

Gated tools (anything in policy.yaml as ``human_approval``) MUST also include
a ``render`` callable in their entry. The renderer takes the validated args
dict and returns the markdown text the human approver sees on the Slack card.
This is the ONLY thing the human reads to decide approve/reject — so it must
be derived deterministically from the actual ``args`` that will execute, not
from any caller-supplied summary string. See Dispatcher._render_card_text().
"""

from typing import Any

_AGENT_ID = {
    "type": "string",
    # TRMM's Agent.agent_id is a CharField(max_length=200) generated by the
    # rmmagent installer — typically a ~40-char base62-style alphanumeric
    # token (e.g. "mwMzVttIfCIjBWONqBsuiTJZEbcntWTIKhXSBWot"), but UUIDs are
    # also accepted. The pattern is intentionally permissive *up to the limit
    # of what's safe*: alphanumerics, hyphens, and underscores only — which
    # blocks `.`, `/`, `\`, NUL, and any URL-encoded traversal payload from
    # being interpolated into f"/agents/{agent_id}/cmd/" against TRMM.
    "pattern": r"^[A-Za-z0-9_-]{8,200}$",
    "description": "TRMM agent ID (alphanumeric token issued by the agent installer)",
}
_INT_LIMIT = {"type": "integer", "minimum": 1, "maximum": 200, "default": 20}

SCHEMAS: dict[str, dict[str, Any]] = {
    "list_alerts": {
        "description": (
            "List TRMM alerts. Optionally filter by status (all|unresolved|snoozed), "
            "since timestamp (ISO 8601), or client ID."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "enum": ["all", "unresolved", "snoozed"]},
                "since": {"type": "string", "description": "ISO 8601 timestamp"},
                "client_id": {"type": "integer"},
            },
        },
    },
    "get_alert": {
        "description": "Fetch full detail for one alert by integer ID.",
        "schema": {
            "type": "object",
            "properties": {"alert_id": {"type": "integer"}},
            "required": ["alert_id"],
        },
    },
    "search_past_alerts": {
        "description": "Find historical alerts on a given agent since an ISO timestamp.",
        "schema": {
            "type": "object",
            "properties": {
                "agent_id": _AGENT_ID,
                "since": {"type": "string", "description": "ISO 8601 timestamp"},
            },
            "required": ["agent_id", "since"],
        },
    },
    "acknowledge_alert": {
        "description": "Mark an alert as resolved with an optional note (write).",
        "schema": {
            "type": "object",
            "properties": {
                "alert_id": {"type": "integer"},
                "note": {"type": "string"},
            },
            "required": ["alert_id"],
        },
        "render": lambda args: (
            f"Acknowledge alert {args['alert_id']}"
            + (f"\n\nNote: {args['note']}" if args.get("note") else "")
        ),
    },
    "list_agents": {
        "description": "List TRMM agents. Filter by online status, client ID, or site ID.",
        "schema": {
            "type": "object",
            "properties": {
                "online": {"type": "boolean"},
                "client_id": {"type": "integer"},
                "site_id": {"type": "integer"},
            },
        },
    },
    "get_agent": {
        "description": "Fetch the full record for one agent.",
        "schema": {
            "type": "object",
            "properties": {"agent_id": _AGENT_ID},
            "required": ["agent_id"],
        },
    },
    "agent_recent_checks": {
        "description": "Recent check results for an agent (pass/fail + output).",
        "schema": {
            "type": "object",
            "properties": {"agent_id": _AGENT_ID, "n": _INT_LIMIT},
            "required": ["agent_id"],
        },
    },
    "agent_recent_tasks": {
        "description": "Recent scheduled-task runs for an agent.",
        "schema": {
            "type": "object",
            "properties": {"agent_id": _AGENT_ID, "n": _INT_LIMIT},
            "required": ["agent_id"],
        },
    },
    "agent_patch_state": {
        "description": "Windows Update state: installed, missing, failed, pending-reboot KBs.",
        "schema": {
            "type": "object",
            "properties": {"agent_id": _AGENT_ID},
            "required": ["agent_id"],
        },
    },
    "agent_running_processes": {
        "description": "Live process list from an agent (PID, name, CPU, memory).",
        "schema": {
            "type": "object",
            "properties": {"agent_id": _AGENT_ID},
            "required": ["agent_id"],
        },
    },
    "query_clients": {
        "description": "Return the full client to site tree.",
        "schema": {"type": "object", "properties": {}},
    },
    "script_history": {
        "description": "Recent script runs on an agent (stdout, stderr, retcode).",
        "schema": {
            "type": "object",
            "properties": {"agent_id": _AGENT_ID, "n": _INT_LIMIT},
            "required": ["agent_id"],
        },
    },
    "run_script_on_agent": {
        "description": (
            "Invoke a TRMM-library script by integer ID on an agent. "
            "Cannot ship a script body — only IDs of scripts already in TRMM. (write)"
        ),
        "schema": {
            "type": "object",
            "properties": {
                "agent_id": _AGENT_ID,
                "script_id": {"type": "integer"},
                "args": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["agent_id", "script_id"],
        },
        "render": lambda args: (
            f"Run script #{args['script_id']} on agent `{args['agent_id']}`"
            + (f"\n\nScript args: `{args['args']}`" if args.get("args") else "")
        ),
    },
    "run_inline_command": {
        "description": (
            "Run an arbitrary shell command on an agent. PERMANENTLY GATED — every "
            "invocation requires human approval. (write)"
        ),
        "schema": {
            "type": "object",
            "properties": {
                "agent_id": _AGENT_ID,
                "shell": {"type": "string", "enum": ["cmd", "powershell", "bash"]},
                "command": {"type": "string"},
            },
            "required": ["agent_id", "shell", "command"],
        },
        "render": lambda args: (
            f"Run {args['shell']} command on agent `{args['agent_id']}`:\n\n"
            f"```\n{args['command']}\n```"
        ),
    },
    "kill_process": {
        "description": "Kill a process on an agent by PID. (write)",
        "schema": {
            "type": "object",
            "properties": {
                "agent_id": _AGENT_ID,
                "pid": {"type": "integer"},
            },
            "required": ["agent_id", "pid"],
        },
        "render": lambda args: f"Kill PID {args['pid']} on agent `{args['agent_id']}`",
    },
    "restart_service": {
        "description": (
            "Restart a Windows service on an agent. service_name is the service "
            "short name (e.g. W3SVC, Spooler), not the display name. (write)"
        ),
        "schema": {
            "type": "object",
            "properties": {
                "agent_id": _AGENT_ID,
                "service_name": {"type": "string"},
            },
            "required": ["agent_id", "service_name"],
        },
        "render": lambda args: (
            f"Restart service `{args['service_name']}` on agent `{args['agent_id']}`"
        ),
    },
    "reboot_agent": {
        "description": "Reboot an agent host. (write)",
        "schema": {
            "type": "object",
            "properties": {"agent_id": _AGENT_ID},
            "required": ["agent_id"],
        },
        "render": lambda args: f"Reboot agent `{args['agent_id']}`",
    },
}
