logging:
  receivers:
    auth_log:
      type: files
      include_paths: [/var/log/auth.log]
    syslog:
      type: files
      include_paths: [/var/log/syslog]
    nginx_access:
      type: files
      include_paths:
        - /var/log/nginx/access.log
        - /var/log/nginx/frontend-access.log
        - /rmm/api/tacticalrmm/tacticalrmm/private/log/access.log
    nginx_error:
      type: files
      include_paths:
        - /var/log/nginx/error.log
        - /var/log/nginx/frontend-error.log
    trmm_django:
      type: files
      include_paths:
        - /rmm/api/tacticalrmm/tacticalrmm/private/log/django_debug.log
        - /rmm/api/tacticalrmm/tacticalrmm/private/log/trmm_debug.log
        - /rmm/api/tacticalrmm/tacticalrmm/private/log/error.log
    mesh_errors:
      type: files
      include_paths: [/meshcentral/meshcentral-data/mesherrors.txt]
    trmm_audit_export:
      type: files
      include_paths: [/var/log/nanormm/audit-export.jsonl]
  service:
    pipelines:
      qsrmm:
        receivers: [auth_log, syslog, nginx_access, nginx_error, trmm_django, mesh_errors, trmm_audit_export]
